### ISSUE TITLE
Это не проблема

### ISSUE THREAD

**Issue by pendosio** [IEnumerablee/Volleyball#1]
На деле, я хочу связаться с разработчиком этого замечательного плагина, и мб даже заказать плагин или позвать в команду, я оставлю свой дискорд на всякий penuch_

**Comment by MrSculk1945** [comment]
> На заказ я вряд ли, что писать буду. Команда у меня своя есть на проекте, что я пилю. Дискорд мой - ienumerable. Если нужен.
Слуууушай у меня не работает на 1.20.4... Ядро purpur. Можешь посоветовать что нибудь чтоб решить?
