### ISSUE TITLE
Не работает на 1.20.4. Ядро purpur

### ISSUE THREAD

**Issue by MrSculk1945** [IEnumerablee/Volleyball#15]
Когда нажимаю на фугу кожей то просто появляеться обыкновенный армор стенд... Может дело в ядре?
Помогите кто разбираеться, заранее спасибо :)

**Comment by ksyshechkaa** [comment]
плагин не работает на 1.20.4

**Comment by MrSculk1945** [comment]
А на каких версиях работает? И будкт ли обновление?

пн, 6 мая 2024 г., 19:18 Ksyusha ***@***.***>:

**Comment by IEnumerablee** [comment]
https://github.com/IEnumerablee/Volleyball/releases/tag/v1.4(1.20.4)
