### ISSUE TITLE
Как скачать

### ISSUE THREAD

**Issue by Danik4ek** [IEnumerablee/Volleyball#3]
Я очень тупой, пж обьясните как и то грузить на сервак

**Comment by stngularity** [comment]
https://github.com/IEnumerablee/Volleyball/releases/tag/v1.4
там в `Assets` ищешь [`Volleyball-1.4.jar`](https://github.com/IEnumerablee/Volleyball/releases/download/v1.4/Volleyball-1.4.jar) и скачиваешь
