### ISSUE TITLE
как установить я нечего не понял не где не написанно куда кидать эти файлы помогите пожайлуста

### ISSUE THREAD

**Issue by VanyaClash** [IEnumerablee/Volleyball#9]

**Comment by VanyaClash** [comment]
куда кидать фалы чтобы заработало

**Comment by Danik4ek** [comment]
https://github.com/IEnumerablee/Volleyball/releases/tag/v1.4
там в Assets ищешь [Volleyball-1.4.jar](https://github.com/IEnumerablee/Volleyball/releases/download/v1.4/Volleyball-1.4.jar) и скачиваешь . И закидываешь в папку plugin на сервере

**Comment by killua028** [comment]
здравствуйте, актуальны еще вопросы по этому плагину?
